export const THEORY_DOMAINS = {
  "Artificial Intelligence & Machine Learning": [
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Reinforcement Learning",
    "Federated Learning",
    "Explainable AI",
    "Other",
  ],
  "Data Science & Analytics": [
    "Big Data Analytics",
    "Predictive Modelling",
    "Data Visualisation",
    "Statistical Analytics",
    "Data Engineering",
    "Other",
  ],
  "Cybersecurity & Digital Forensics": [
    "GIS Analytics & Crime Prediction",
    "Network Security",
    "Digital Forensics",
    "Cryptography & PKI",
    "Cloud Security",
    "Ethical Hacking",
    "IoT Security",
    "Privacy & Data Protection",
    "Other",
  ],
  "Cloud Computing & DevOps": [
    "Serverless Architecture",
    "CI/CD & DevSecOps",
    "Kubernetes & Containerisation",
    "Microservices",
    "Other",
  ],
  "Mobile and Web Technologies": [
    "Progressive Web Apps",
    "Cross-Platform Mobile",
    "Other",
  ],
  "IoT & Embedded Systems": [
    "Industrial IoT",
    "Edge Computing",
    "Embedded Systems",
    "Robotics",
    "Drone Technology",
    "Other",
  ],
  "Blockchain Technology": [
    "Smart Contracts",
    "DeFi & Web3",
    "Blockchain Applications",
    "Digital Identity",
    "Other",
  ],
  "Computer Networks & Communication Technologies": [
    "Computer Networks",
    "Wireless Networks",
    "5G/6G Networks",
    "Software Defined Networking (SDN)",
    "Network Virtualization (NFV)",
    "Wireless Sensor Networks",
    "Network Monitoring",
    "Routing & Switching",
    "Cloud Networking",
    "Optical Communication",
    "Other",
  ],
  "Any Other Emerging Technology": [
    "Quantum Computing",
    "Extended Reality (AR/VR)",
    "Other",
  ],
  "Other": ["Other"],
};

export const CODING_DOMAINS = {
  "Arrays": ["Traversal", "Prefix Sum", "Difference Array", "Kadane's Algorithm", "Two Pointers", "Sliding Window", "Rotation", "Sorting", "Searching", "Frequency Counting", "Other"],
  "Strings": ["Pattern Matching", "Anagrams", "Palindrome", "Substrings", "String Compression", "KMP", "Rabin-Karp", "Z Algorithm", "Trie-based String Search", "Rolling Hash", "Other"],
  "Searching": ["Linear Search", "Binary Search", "Ternary Search", "Binary Search on Answer", "Search in Rotated Array", "Other"],
  "Sorting": ["Bubble", "Selection", "Insertion", "Merge Sort", "Quick Sort", "Heap Sort", "Counting Sort", "Radix Sort", "Bucket Sort", "Custom Comparator", "Other"],
  "Recursion": ["Recursive Thinking", "Tail Recursion", "Divide & Conquer", "Other"],
  "Backtracking": ["N-Queens", "Sudoku Solver", "Permutations", "Combinations", "Subsets", "Rat in a Maze", "Word Search", "Other"],
  "Bit Manipulation": ["XOR Tricks", "Bit Masking", "Set/Clear Bits", "Power of Two", "Gray Code", "Bit DP", "Other"],
  "Mathematics": ["GCD & LCM", "Prime Numbers", "Sieve of Eratosthenes", "Modular Arithmetic", "Combinatorics", "Number Theory", "Matrix Exponentiation", "Other"],
  "Greedy Algorithms": ["Interval Scheduling", "Activity Selection", "Huffman Coding", "Fractional Knapsack", "Job Sequencing", "Other"],
  "Dynamic Programming (DP)": ["1D DP", "2D DP", "Knapsack", "LIS", "LCS", "Matrix Chain Multiplication", "Digit DP", "Bitmask DP", "Tree DP", "DP on Graphs", "Other"],
  "Stacks": ["Monotonic Stack", "Expression Evaluation", "Next Greater Element", "Histogram Problems", "Parentheses Matching", "Other"],
  "Queues": ["Circular Queue", "Deque", "Monotonic Queue", "BFS Queue Applications", "Other"],
  "Linked Lists": ["Singly", "Doubly", "Circular", "Fast & Slow Pointer", "Reverse List", "Merge Lists", "Cycle Detection", "Other"],
  "Trees": ["Binary Tree", "Binary Search Tree", "AVL Tree", "Segment Tree", "Fenwick Tree (BIT)", "Trie", "Tree Traversals", "Lowest Common Ancestor", "Other"],
  "Heaps / Priority Queue": ["Min Heap", "Max Heap", "Heap Sort", "Top-K Problems", "Median Maintenance", "Other"],
  "Graphs": ["BFS", "DFS", "Connected Components", "Cycle Detection", "Bipartite Graph", "Topological Sort", "MST (Prim/Kruskal)", "Shortest Path (Dijkstra, Bellman-Ford, Floyd-Warshall)", "Union-Find", "SCC", "Other"],
  "Hashing": ["Hash Map", "Hash Set", "Frequency Map", "Custom Hashing", "Other"],
  "Two Pointers": ["Opposite Direction", "Same Direction", "Fast & Slow Pointer", "Other"],
  "Sliding Window": ["Fixed Window", "Variable Window", "Maximum/Minimum Window Problems", "Other"],
  "Prefix Sum": ["1D Prefix Sum", "2D Prefix Sum", "Difference Array", "Other"],
  "Binary Search": ["Standard Binary Search", "Lower Bound", "Upper Bound", "Binary Search on Answer", "Other"],
  "Divide & Conquer": ["Merge Sort", "Quick Sort", "Closest Pair", "Binary Exponentiation", "Other"],
  "Union Find (DSU)": ["Path Compression", "Union by Rank", "Dynamic Connectivity", "Other"],
  "Trie": ["Prefix Search", "Dictionary", "Auto-complete", "XOR Trie", "Other"],
  "Segment Tree": ["Range Query", "Lazy Propagation", "Point Updates", "Other"],
  "Fenwick Tree (BIT)": ["Prefix Queries", "Range Updates", "Other"],
  "Monotonic Data Structures": ["Monotonic Stack", "Monotonic Queue", "Other"],
  "Intervals": ["Merge Intervals", "Insert Interval", "Sweep Line", "Other"],
  "Geometry": ["Convex Hull", "Line Sweep", "Orientation Test", "Closest Pair", "Other"],
  "Game Theory": ["Nim Game", "Grundy Numbers", "Minimax", "Other"],
  "Probability": ["Expected Value", "Randomized Algorithms", "Other"],
  "Computational Geometry": ["Polygon Area", "Convex Hull", "Line Intersection", "Other"],
  "Network Flow": ["Max Flow", "Min Cut", "Bipartite Matching", "Other"],
  "Advanced Graph Algorithms": ["Tarjan's Algorithm", "Kosaraju", "Euler Tour", "Heavy-Light Decomposition", "Other"],
  "Advanced DP": ["DP on Trees", "DP with Bitmask", "State Compression", "Convex Hull Trick", "Other"],
  "Concurrency / Parallel Algorithms": ["Parallel Processing", "Synchronization Concepts", "Other"],
  "Miscellaneous": ["Simulation", "Implementation", "Ad Hoc Problems", "Constructive Algorithms", "Other"],
  "Other": ["Other"],
};

export type TheoryDomainKey = keyof typeof THEORY_DOMAINS;
export type CodingDomainKey = keyof typeof CODING_DOMAINS;
